### ISSUE TITLE
Likely wrong PHP version declaration

### ISSUE THREAD

**Issue by arokettu** [mezzio/mezzio-cors#45]
PHP declaration in composer.json feels wrong:

```php
"php": "^7.4 || ^8.0 || ~8.1.0"
```

it should either be `"^7.4 || ~8.0.0 || ~8.1.0"` like in other mezzio packages to control PHP 8.x support or `"^7.4 || ^8.0"` to show that any 8.x is supported

Not really a bug but a smelly declaration

**Comment by Ocramius** [comment]
Related: https://github.com/mezzio/mezzio-cors/pull/44#issuecomment-1259244386

Feel free to send a patch with the adjustment: it is 100% an oversight.

**Comment by Ocramius** [comment]
Note: please target `1.5.x` if you do.

**Comment by boesing** [comment]
@Ocramius do you mean 1.4.x? I would just release 1.4.1 with the fixed constraints so that 1.5.0 can provide new features.
Or do you think that would be problematic?

**Comment by Ocramius** [comment]
We should probably not change constraints in a patch release: messes with upgrade path 🤔

**Comment by boesing** [comment]
That would only affect users on PHP 8.2 whic hare using this component. Since it highly depends on mezzio itself (which has proper constraints), these upstream projects already used `--ignore-platform-req=php` anyways and thus, I'd say, it would be fine?

I'd change to `~7.4.0 || ~8.0.0 || ~8.1.0` for now.


https://github.com/mezzio/mezzio-router/blob/cfd6f24991ba3dfc88d5fe7ab2af30a2d766130d/composer.json#L38

**Comment by Ocramius** [comment]
Your pick, but I personally avoid touching `composer.json` on stable branches :D

**Comment by boesing** [comment]
I tend to agree in case we would limit stuff. But actually we do stricten the php constraint to ensure we provide proper 8.2 support in the next minor for example.

What kind of problems did you ran in, maybe I can get a better feeling on this when I understand the problems which might occur. 

As of now, users are already able to install this component on PHP 8.2 which could be a problem. Luckily, mezzio-router does not yet allow PHP 8.2 and thus, its only installable when some1 is actively ignoring PHP platform requirement.
If we now just change `^8.0 || ~8.1.0` to `~8.0.0 || ~8.1.0`, this would be okayish and does not limit anyone in upgrading?

If this would be a component instead, I would agree 100% but since we are talking about an accidentally widened PHP constraint, this might be okayish?

**Comment by Ocramius** [comment]
Fine by me :+1:

**Comment by Ocramius** [comment]
Handled in #46
